export const searchIssuesMapping = {
  "total_count": 280,
  "incomplete_results": false,
  "items": [
    {
      "url": "https://vm-github.wiremockapi.cloud/repos/abc/vm-azure-func/issues/12",
      "repository_url": "https://vm-github.wiremockapi.cloud/repos/abc/vm-azure-func",
      "labels_url": "https://vm-github.wiremockapi.cloud/repos/abc/vm-azure-func/issues/12/labels{/name}",
      "comments_url": "https://vm-github.wiremockapi.cloud/repos/abc/vm-azure-func/issues/12/comments",
      "events_url": "https://vm-github.wiremockapi.cloud/repos/abc/vm-azure-func/issues/12/events",
      "html_url": "https://github.com/abc/vm-azure-func/pull/12",
      "id": 2916867523,
      "node_id": "PR_kwDON9MtDs6Of05a",
      "number": 12,
      "title": "SCRUM-2 jira demo changes",
      "user": {
        "login": "def",
        "id": 200214543,
        "node_id": "U_kgDOC-8IDw",
        "avatar_url": "https://avatars.githubusercontent.com/u/200214543?v=4",
        "gravatar_id": "",
        "url": "https://vm-github.wiremockapi.cloud/users/def",
        "html_url": "https://github.com/def",
        "followers_url": "https://vm-github.wiremockapi.cloud/users/def/followers",
        "following_url": "https://vm-github.wiremockapi.cloud/users/def/following{/other_user}",
        "gists_url": "https://vm-github.wiremockapi.cloud/users/def/gists{/gist_id}",
        "starred_url": "https://vm-github.wiremockapi.cloud/users/def/starred{/owner}{/repo}",
        "subscriptions_url": "https://vm-github.wiremockapi.cloud/users/def/subscriptions",
        "organizations_url": "https://vm-github.wiremockapi.cloud/users/def/orgs",
        "repos_url": "https://vm-github.wiremockapi.cloud/users/def/repos",
        "events_url": "https://vm-github.wiremockapi.cloud/users/def/events{/privacy}",
        "received_events_url": "https://vm-github.wiremockapi.cloud/users/def/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "labels": [],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2025-03-13T11:44:32Z",
      "updated_at": "2025-03-13T13:41:04Z",
      "closed_at": "2025-03-13T13:41:04Z",
      "author_association": "COLLABORATOR",
      "sub_issues_summary": {
        "total": 0,
        "completed": 0,
        "percent_completed": 0
      },
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
        "url": "https://vm-github.wiremockapi.cloud/repos/abc/vm-azure-func/pulls/12",
        "html_url": "https://github.com/abc/vm-azure-func/pull/12",
        "diff_url": "https://github.com/abc/vm-azure-func/pull/12.diff",
        "patch_url": "https://github.com/abc/vm-azure-func/pull/12.patch",
        "merged_at": "2025-03-13T13:41:04Z"
      },
      "body": null,
      "reactions": {
        "url": "https://vm-github.wiremockapi.cloud/repos/abc/vm-azure-func/issues/12/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
      },
      "timeline_url": "https://vm-github.wiremockapi.cloud/repos/abc/vm-azure-func/issues/12/timeline",
      "performed_via_github_app": null,
      "state_reason": null,
      "score": 1
    }]
}